### ISSUE TITLE
Cant build [Win32]: g_crValue undeclared identifier (maybe a typo)

### ISSUE THREAD

**Issue by Kerogi** [ajkhoury/ReClassEx#45]
https://github.com/ajkhoury/ReClassEx/blob/87e1defd19514929909fcc5f7c4992644d6ac9fc/ReClass/CNodeBase.cpp#L532

CNodeBase.cpp(532): error C2065: 'g_crValue': undeclared identifier

**Comment by Timboy67678** [comment]
g_clrValue is the correct name. Typo for sure

**Comment by ajkhoury** [comment]
Stick an 'l' in there and make a pull request 😃

**Comment by ajkhoury** [comment]
fixed in 57fc5bfc1ac040cadfe336bb2243320103bcff32
