### ISSUE TITLE
vtable read faild

### ISSUE THREAD

**Issue by huangfengye** [ajkhoury/ReClassEx#48]
can;t read vtable win7 sp1 Chinese language
https://puu.sh/CIGSV/d5f83f26e3.png

**Comment by huangfengye** [comment]
this is bug still not be fixed.....on WIN10 1809
https://puu.sh/HHVvZ/3b882cbdbe.png

**Comment by ajkhoury** [comment]
Try pressing the little camera icon

**Comment by huangfengye** [comment]
thank.  after pressing the little camera icon, it  work. but why we should do this??xD
